config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/welcome'

  root 'restaurants#welcome'
  post 'get_menu_items' => 'restaurants#get_menu_items'
  get 'search_menu_items' => 'restaurants#search_menu_items'
  get 'search_locations' => 'restaurants#search_locations'

  resources :feedbacks, :locations, :menus do
  end

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :menu

  validates :message, presence: true

  scope :get_menu_feedback_list, ->(menu_id) {where(:menu_id => menu_id).order("created_at desc")}
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :restaurant
  has_many :menus

  validates :name, presence: true
  validates :name, uniqueness: { scope: :restaurant, message: "A branch with such name already exists" }
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :location
  has_many :feedback

  validates :item, presence: true
  validates :day, presence: true
  validates :type_of, presence: true
  validates :item, uniqueness: { scope: :location, message: "A menu item with such name already exists" }

  self.per_page = 5

  scope :get_day_menu, ->(day) { where(:day => day).select(:item,:id, :type_of) }
  scope :get_menu_items, ->(query_string) { uniq.where("item LIKE ?", "%#{query_string}%").pluck(:item) }

  before_create { self.item.downcase! }

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :locations, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
  # accepts_nested_attributes_for :locations, :allow_destroy => true,:reject_if => :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def new
    @feedback = Feedback.new(:menu_id => params[:menu_id])
  end

  def create
    @feedback = Feedback.new(feedback_params)
    if @feedback.save
      redirect_to feedbacks_path(:menu_id => params[:feedback][:menu_id]), notice: "Feedback successfully posted."
    else
      flash[:alert] = @feedback.errors.full_messages.first
      redirect_to new_feedback_path(:menu_id => params[:feedback][:menu_id])
    end
  end

  def index
    @feedbacks = Feedback.get_menu_feedback_list(params[:menu_id]).paginate(:page => params[:page], :per_page => 5)
    @menu = Menu.find(params[:menu_id])
  end

  private
  def feedback_params
    params.require(:feedback).permit(:author, :message, :menu_id)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	def new
		@location = Location.new(:restaurant_id => params[:restaurant_id])
	end

	def create
		@location = Location.new(location_params)
		if @location.save
			redirect_to locations_path(:restaurant_id => params[:location][:restaurant_id]), notice: "Branch successfully created."
		else
			flash[:alert] = @location.errors.full_messages.first
			redirect_to locations_path(:restaurant_id => params[:location][:restaurant_id] )
		end
	end

	def index
		@restaurant = Restaurant.find(params[:restaurant_id])
		@locations = @restaurant.locations
	end

	private
	def location_params
		params.require(:location).permit(:name, :address, :restaurant_id)
	end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
	def new
		@menu = Menu.new(:location_id => params[:location_id])
	end

	def create
		@menu = Menu.create(menu_params)
		if @menu.save
			redirect_to menus_path(:location_id => params[:menu][:location_id]), notice: "Menu successfully created."
		else
			flash[:alert] = @menu.errors.full_messages.first
			redirect_to menus_path(:location_id => params[:menu][:location_id])
		end
	end

	def index
		@location = Location.find(params[:location_id])
		@menu_list = @location.menus
	end

	private
	def menu_params
		params.require(:menu).permit(:item, :type_of, :day, :location_id)
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def welcome
    @restaurant = Restaurant.first
    @locations = @restaurant.locations
  end

  def get_menu_items
    if params[:location_id].present? && params[:day].present?
      @location = Location.find(params[:location_id])
      @menu_items = Location.find(params[:location_id]).menus.get_day_menu(params[:day])
    else
      redirect_to root_url, notice: "Please select branch and day."
    end
  end

  def search_menu_items
    if params[:query]
      @menu_items = Menu.get_menu_items(params[:query].downcase)
    else
      @menu_items = Menu.all
    end

    respond_to do |format|
      format.json { render json: @menu_items }
    end
  end

  def search_locations
    @menu = Menu.where(:item => params[:menu]).includes(:location)
  end

  # def new_location
  #   @restaurant = Restaurant.first
  #   @restaurant.locations.build(:restaurant_id => @restaurant.id)
  #   # respond_with @restaurant
  # end

  # def create_locations
  #   @restaurant = Restaurant.first
  #   if @restaurant.update_attributes(restaurant_params)
  #     flash[:success] = "Created/Updated Locations"
  #     redirect_to locations_path
  #   else
  #     flash[:alert] = @restaurant.errors.full_messages.first
  #     redirect_to edit_locations_path
  #   end
  # end

  # private
  # def restaurant_params
  #   params.require(:restaurant).permit(:name, locations_attributes: [:name, :address])
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
	def display_menu(menu)
		menu.item.capitalize	
	end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def get_greet_message(restaurant_name)
    t = Time.now.hour
    greet = case
    when t < 12
      "Good Morning!"
    when (12..15) === t
      "Good Afternoon!"
    when t > 15
      "Good Evening!"
    else
      "Hello!"
    end
    greet + " Welcome to #{restaurant_name} online menu/location search."
  end
end

app/views/feedbacks/index.haml
%h1
%br
%p Feedback List for #{@menu.item} at #{@menu.location.name}
%p
%table.table.table-striped
  %tr
    %th Author
    %th Feedback Message
  - @feedbacks.each do |feedback|
    %tr
      %td
        = feedback.author
      %td
        = feedback.message

= will_paginate @feedbacks
%br
= link_to "Give feedback", new_feedback_path(:menu_id => @menu.id)

app/views/feedbacks/new.haml
%div{:style => "margin-top:50px;"}
  %p
    %b Feedback Form
  = simple_form_for @feedback, url: feedbacks_path, via: 'post', as: 'feedback'  do |f|
    = f.hidden_field :menu_id
    = f.input :author, placeholder: 'Author Name'
    = f.input :message, placeholder: 'Give your feedback'
    = f.button :submit

app/views/layouts/_header.haml
= link_to "Home", root_path
|
= link_to "Admin Panel", locations_path(:restaurant_id => "#{Restaurant.first.id}")

app/views/layouts/application.haml
!!!
%html
  %head
    %title OnlineMenu
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fixed
      =render :partial => "layouts/header", :formats => :haml
      - flash.each do |name, msg|
        = content_tag :div, msg, class: name
      = yield

app/views/locations/index.haml
%h1
%br

= link_to "Add Branch", new_location_path(:restaurant_id => params[:restaurant_id])

%p Branches List for #{@restaurant.name}
%p
%table.table.table-striped
  %tr
    %th Branch Name
    %th Address
    %th Add Menu
    %th View Menu
  - @locations.each do |location|
    %tr
      %td
        = location.name
      %td
        = location.address
      %td
        = link_to "Add Menu", new_menu_path(:location_id => location.id)
      %td
        = link_to "View Menu", menus_path(:location_id => location.id)

/ = will_paginate @locations
/ %br
/ = link_to "Give feedback", new_feedback_path(:menu_id => @menu.id)

app/views/locations/new.haml
= simple_form_for(@location, :url => locations_path, :html => { :method => :post, :role => "form form-horizontal"}) do |f|
  = f.hidden_field :restaurant_id
  = f.input :name, :label => "Branch Name"
  = f.input :address, :lable => "Address"
  = f.button :submit

app/views/menus/index.haml
%h1
%br
%p Menu Item List for #{@location.restaurant.name} in #{@location.name}
%p
%table.table.table-striped
  %tr
    %th Menu Item
    %th Type of menu
    %th Availability
  - @menu_list.each do |menu|
    %tr
      %td
        = display_menu(menu)
      %td
        = menu.type_of
      %td
        = menu.day

= link_to "Add Menu", new_menu_path(:location_id => @location.id)

app/views/menus/new.haml
= simple_form_for(@menu, :url => menus_path, :html => { :method => :post, :role => "form form-horizontal"}) do |f|
  = f.hidden_field :location_id
  = f.input :item, :label => "Menu Item", :placeholder => "eg: Idly, Dosa"
  = f.input :type_of, :label => "Type of Menu", :placeholder => "eg: Breakfast, Dinner"
  = f.select :day, options_for_select(Date::DAYNAMES), prompt: "Select Day"
  %br
  %br
  = f.button :submit

app/views/restaurants/get_menu_items.haml
%h1
%br
- if @menu_items.present?
  %p Menu Items for #{@location.name} on #{params[:day]}
  %table.table.table-striped
    %tr
      %th Menu Item
      %th Availability
      %th Feedback
      %th Feedback List

    - @menu_items.each do |menu|
      %tr
        %td
          = menu.item
        %td
          = menu.type_of
        %td
          = link_to "Give feedback", new_feedback_path(:menu_id => menu.id)
        %td
          = link_to "View feedback list", feedbacks_path(:menu_id => menu.id)
-else
  %p No Menu for #{@location.name} on #{params[:day]}
  = link_to "Add Menu", new_menu_path(:location_id => @location.id)

app/views/restaurants/new.haml
%div{:style => "margin-top:50px;"}
  %p
    %b Feedback Form
  = simple_form_for @restaurant, url: feedbacks_path, via: 'post', as: 'feedback'  do |f|
    = f.hidden_field :menu_id
    = f.input :author, placeholder: 'Author Name'
    = f.input :message, placeholder: 'Give your feedback'
    = f.button :submit

app/views/restaurants/new_location.haml
= simple_form_for(@restaurant, :url => create_locations_path, :html => { :method => :post, :role => "form form-horizontal"}) do |f|
  =f.fields_for :locations do |location|
    = location.input :name, :label => "Branch Name"
    = location.input :address, :lable => "Address"
  = f.button :submit

app/views/restaurants/search_locations.haml
%table.table.table-striped
  %tr
    %th Branch
    %th Address
    %th Day
    %th Availability
    %th Feedback
    %th Feedback List

  - @menu.each do |menu|
    %tr
      %td
        =menu.location.name
      %td
        =menu.location.address
      %td
        =menu.day
      %td
        =menu.type_of
      %td
        = link_to "Give feedback", new_feedback_path(:menu_id => menu.id)
      %td
        = link_to "View feedback list", feedbacks_path(:menu_id => menu.id)

app/views/restaurants/welcome.html.haml
%h1
  =get_greet_message(@restaurant.name)


= form_tag("/search_locations", method: "get") do
  = label_tag(:menu, "Search by Menu")
  %input#search{:autocomplete => "off", :input => "text", :name => "menu"}/
  = submit_tag("Search")

%h3 OR

= form_tag("/get_menu_items", method: "post") do
  = label_tag(:q, "Search for:")
  = select_tag "location_id", options_from_collection_for_select(@locations, "id", "name"), prompt: "Select branch"

  = select_tag "day", options_for_select(Date::DAYNAMES), prompt: "Select Day"
  = submit_tag("Search")

= javascript_include_tag "load_typeahead"